name: PHP CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Krok 1: Získání kódu z repozitáře
      - name: Checkout code
        uses: actions/checkout@v3

      # Krok 2: Nastavení PHP 8.1
      - name: Set up PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Nastavení verze PHP (8.0, 8.1, nebo 8.2)
          extensions: mbstring, intl, pdo_mysql # Rozšíření PHP
          ini-values: |
            memory_limit=2G # Nastavení hodnot v php.ini
          coverage: none # Povolení nebo zakázání Xdebug

      # Krok 3: Instalace závislostí pomocí Composeru
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Krok 4: Spuštění testů
      - name: Run tests
        run: vendor/bin/phpunit --testdox
